[manager]
show_hidden = true # Show hidden files

[plugin]
prepend_preloaders = [
  # Disable Image
  { mime = "image/{avif,hei?,jxl,svg+xml}", run = "noop" },
  { mime = "image/*", run = "noop" },
  # Disable Video
  { mime = "video/*", run = "noop" },
  # Disable PDF
  { mime = "application/pdf", run = "noop" },
]

prepend_previewers = [
  # Use file instead
  { mime = "image/{avif,hei?,jxl,svg+xml}", run = "file" },
  { mime = "image/*", run = "file" },
  { mime = "video/*", run = "file" },
  { mime = "application/pdf", run = "file" },
]
